name: Deploy Functions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Repo'yu klonla
      - name: Check out
        uses: actions/checkout@v3

      # 2) Node sürümünü ayarla
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) GCP Auth (Service Account üzerinden)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # 4) Firebase CLI kur
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5) Functions bağımlılıklarını kur
      - name: Install functions dependencies
        run: |
          cd functions
          npm install
        # "npm run build" vb. varsa burada ekleyebilirsiniz

        # 6) Firebase Config Ayarlarını Yapılandırma
      - name: Set Firebase Config
        run: |
          firebase functions:config:set sql.user="${{ secrets.SQL_USER }}" \
                                        sql.password="${{ secrets.SQL_PASSWORD }}" \
                                        sql.server="${{ secrets.SQL_SERVER }}" \
                                        sql.port="${{ secrets.SQL_PORT }}" \
                                        sql.database="${{ secrets.SQL_DATABASE }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


      # 7) Deploy only functions (Artık FIREBASE_TOKEN'a gerek yok)
      - name: Firebase Deploy (Functions Only)
        run: firebase deploy --only functions
